export const logoData = [
  {
    lightFilePath: "/img/spotify-white.png",
    darkFilePath: "/img/spotify-black.png",
    alt: "spotify logo",
    href: "https://open.spotify.com/show/1lKHRsuf2qen2PlnkjEFNV?si=7c44632705e64f66",
    key: "spot",
    required: true,
  },
  {
    lightFilePath: "/img/youtube-white.png",
    darkFilePath: "/img/youtube-black.png",
    alt: "youtube logo",
    href: "https://www.youtube.com/@ExistencePod",
    key: "yt",
    required: true,
  },
  {
    lightFilePath: "/img/apple-white.png",
    darkFilePath: "/img/apple-black.png",
    alt: "apple logo",
    href: "https://podcasts.apple.com/us/podcast/existence/id1636717921",
    key: "appl",
    required: true,
  },
  {
    // TODO: Get discord URL
    lightFilePath: "/img/discord-white.png",
    darkFilePath: "/img/discord-black.png",
    alt: "discord logo",
    href: "",
    key: "discord",
    tailwindCSS: "hidden md:block",
    required: false,
  },
  {
    lightFilePath: "/img/instagram-white.png",
    darkFilePath: "/img/instagram-black.png",
    alt: "instagram logo",
    href: "https://www.instagram.com/existencepod/",
    key: "ig",
    tailwindCSS: "hidden md:block",
    required: false,
  },
];
